recipes = [
    # "set-hostname",
    "persist-root-home",
    "ssh",
    "zsh",

    # wifi credentials are required as Raspberry Pi Zero's don't have an ethernet adapter
    "set-wifi",
]

# Make image generic so it can be used for pi4 and pi5
# So to either pi4 or pi5 if you want to build pi specific images which include the given firmware (EEPROM)
include_firmware = "none"

boot_flow = "u-boot"

[parameters.set-hostname]
hostname = "tedge-rugpi"

[parameters.apt-cleanup]
autoremove = true

[parameters.ssh]
root_authorized_keys = """
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfhQGWWw73ponAokdNSRZ5cQc9/CIX1TLQgYlr+BtObKoO4UNFP1YSbgK03GjhjeUid+QPmV+UURqxQTqLQoYWqUFP2CYkILFccVPmTvx9HLwupI+6QQKWfMDx9Djfph9GzInymaA5fT7hKppqittFrC/l3lkKgKTX5ohEOGshIbRgtgOYIaW3ByTx3urnaBbYCIgOyOZzSIyS0dUkwsiLu3XjPspgmn3Fs/+vofT/yhBe1carW0UM3ivV0JFfJzrxbCl/F7I2qwfjZXsypjkwlpNupUMuo3xPMi8YvNvyEu4d+IEAqO1dCcdGcxlkiHxrdITIpVLt5mjJ2LauHE/H bootstrap
"""

[parameters.set-wifi]
# These values should be modified if you want to enable default wifi credentials in the image
ssid = "onboarding_jail"
password = "onboarding_jail"

[parameters.rugpi-ctrl]
rugpi_admin = true  # Enable Rugpi Admin.