name: Bake Image

on:
  push:
    branches:
      - main
      - ci

env:
  PI_BASE_IMAGE: "https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2023-10-10/2023-10-10-raspios-bookworm-arm64-lite.img.xz"

jobs:
  bake-image:
    name: Bake Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: extractions/setup-just@v1

      - name: Install QEMU
        run: docker run --privileged --rm tonistiigi/binfmt --install arm64

      - name: Set image version
        run: echo "VERSION=$(just generate_version)" >> $GITHUB_ENV

      - name: Build image
        run: just build-all-variants

      - name: Upload Image
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: build/*.xz
