name: Bake Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci

jobs:
  info:
    name: Build information
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.step1.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: extractions/setup-just@v1
      - id: step1
        run: echo "version=$(just generate_version)" >> "$GITHUB_OUTPUT"

  bake-image:
    name: Bake Image ${{ matrix.job.arch }} - ${{ matrix.job.profile }} - ${{ matrix.job.variant }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - { arch: armhf, profile: armhf, variant: pi01 }
          - { arch: arm64, profile: default, variant: pi023 }
          - { arch: arm64, profile: default, variant: pi4 }
          - { arch: arm64, profile: default, variant: pi45 }
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: extractions/setup-just@v1
      - name: Build image
        env:
          VERSION: ${{needs.info.outputs.version}}
        run: |
          mkdir build
          just IMAGE_ARCH=${{ matrix.job.arch }} PROFILE=${{ matrix.job.profile }} VARIANT=${{ matrix.job.variant }} build-all

      - name: Upload Image
        uses: actions/upload-artifact@v3
        with:
          name: tedge_rugpi_${{matrix.job.profile}}_${{matrix.job.variant}}_${{version}}
          path: build/tedge_rugpi_${{matrix.job.profile}}_${{matrix.job.variant}}_${{version}}*.xz
