name: Bake Image

on:
  push:
    branches:
      - main
      - ci

env:
  PI_BASE_IMAGE: "https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2023-10-10/2023-10-10-raspios-bookworm-arm64-lite.img.xz"

jobs:
  bake-image:
    name: Bake Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: extractions/setup-just@v1

      - name: Set image name
        run: echo "IMAGE_NAME=$(just generate_version tedge_rugpi_45)" >> $GITHUB_ENV

      - name: Install QEMU
        run: docker run --privileged --rm tonistiigi/binfmt --install arm64

      - name: Set Image
        run: just set-image images/pi45.toml

      - name: Extract Image
        run: just extract

      - name: Customize System
        run: just customize

      - name: Bake Image
        run: just bake

      - name: Upload Image
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.IMAGE_NAME }}
          path: build/${{ env.IMAGE_NAME }}*.img
